// この配列に1作品ずつ追加します。developmentOrder の小さい順が初期表示です。
// 画像のパスはこの /games/ フォルダーからの相対パスです。
// 詳しい登録方法は README.md を参照してください。
window.portfolioGames = [
    {
        title: "素因数分解",
        image: "information/PrimeFactorization/PrimeFactorization_1_Square.png", // 例: "images/my-game.webp"
        imageAlt: "素因数分解", // 例: "森のステージを探索するゲーム画面"
        detailImages: [
            "information/PrimeFactorization/PrimeFactorization_2.png",
            "information/PrimeFactorization/PrimeFactorization_1.png",
        ],
        tags: ["数学", "パズル", "2D"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2023年夏",
        developmentOrder: 1, // 非表示の並べ替え値。小さい値ほど古い（全作品で基準を統一）
        teamSizeCount: 1, // 分類用の人数。表示用 teamSize とは別に指定
        introductionPath: "information/PrimeFactorization/introduction.txt",
        detailsPath: "information/PrimeFactorization/details.txt",
    },
    {
        title: "SPS ~セカンド・パーソン・シューティング~",
        image: "information/SPS/SPS_1_Square.png",
        imageAlt: "SPS ~セカンド・パーソン・シューティング~",
        detailImages: [
            "information/SPS/SPS_2.png",
            "information/SPS/SPS_1.png",
        ],
        tags: ["パズル", "アクション", "3D"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2024年春",
        developmentOrder: 2,
        teamSizeCount: 1,
        introductionPath: "information/SPS/introduction.txt",
        detailsPath: "information/SPS/details.txt",
    },
    {
        title: "Pointer",
        image: "information/Pointer/Pointer_1_Square.png",
        imageAlt: "Pointer",
        detailImages: [
            "information/Pointer/Pointer_2.png",
            "information/Pointer/Pointer_1.png",
        ],
        tags: ["パズル", "2D"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2024年夏",
        developmentOrder: 3,
        teamSizeCount: 1,
        introductionPath: "information/Pointer/introduction.txt",
        detailsPath: "information/Pointer/details.txt",
    },
    {
        title: "学祭用Launcher",
        image: "information/Launcher/Launcher_1_Square.png",
        imageAlt: "学祭用Launcher",
        detailImages: [
            "information/Launcher/Launcher_1.png",
            "information/Launcher/Launcher_2.png",
            "information/Launcher/Launcher_3.png",
            "information/Launcher/Launcher_4.png",
        ],
        tags: ["非ゲーム"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2024年夏",
        developmentOrder: 4,
        teamSizeCount: 1,
        introductionPath: "information/Launcher/introduction.txt",
        detailsPath: "information/Launcher/details.txt",
    },
    {
        title: "the Box",
        image: "information/theBox/theBox_Title.png",
        imageAlt: "the Box",
        detailImages: [
            "information/theBox/theBox_3.png",
            "information/theBox/theBox_1.png",
            "information/theBox/theBox_2.png",
        ],
        tags: ["謎解き", "脱出", "3D"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2024年夏",
        developmentOrder: 5,
        teamSizeCount: 1,
        introductionPath: "information/theBox/introduction.txt",
        detailsPath: "information/theBox/details.txt",
    },
    {
        title: "スクリーンランナー",
        image: "information/ScreenRunner/ScreenRunner_1_Square.png",
        imageAlt: "スクリーンランナー",
        detailImages: [
            "information/ScreenRunner/ScreenRunner_1.png",
        ],
        tags: ["アクション", "オートスクロール", "2D"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2024年秋",
        developmentOrder: 6,
        teamSizeCount: 1,
        introductionPath: "information/ScreenRunner/introduction.txt",
        detailsPath: "information/ScreenRunner/details.txt",
    },
    {
        title: "Sort Visualizer",
        image: "information/SortVisualizer/SortVisualizer_1_Square.png",
        imageAlt: "Sort Visualizer",
        detailImages: [
            "information/SortVisualizer/SortVisualizer_1.png",
        ],
        tags: ["非ゲーム"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2024年冬",
        developmentOrder: 7,
        teamSizeCount: 1,
        introductionPath: "information/SortVisualizer/introduction.txt",
        detailsPath: "information/SortVisualizer/details.txt",
    },
    {
        title: "The 複素数平面",
        image: "information/TheComplexPlane/TheComplexPlane_Title.png",
        imageAlt: "The 複素数平面",
        detailImages: [
            "information/TheComplexPlane/TheComplexPlane_2.png",
            "information/TheComplexPlane/TheComplexPlane_1.png",
        ],
        tags: ["数学", "パズル"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2025年春",
        developmentOrder: 8,
        teamSizeCount: 1,
        introductionPath: "information/TheComplexPlane/introduction.txt",
        detailsPath: "information/TheComplexPlane/details.txt",
    },
    {
        title: "プレゼント交換会用 組み合わせ決めツール",
        image: "information/GiftExchanger/GiftExchanger_1_Square.png",
        imageAlt: "プレゼント交換会用 組み合わせ決めツール",
        detailImages: [
            "information/GiftExchanger/GiftExchanger_2.png",
            "information/GiftExchanger/GiftExchanger_1.png",
        ],
        tags: ["非ゲーム"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2025年夏",
        developmentOrder: 9,
        teamSizeCount: 1,
        introductionPath: "information/GiftExchanger/introduction.txt",
        detailsPath: "information/GiftExchanger/details.txt",
    },
    {
        title: "DREAM",
        image: "information/Dream/Dream_1_Square.png",
        imageAlt: "DREAM",
        detailImages: [
            "information/Dream/Dream_2.jpg",
            "information/Dream/Dream_1.jpg",
        ],
        tags: ["アクション", "タワーディフェンス", "3D"],
        engine: "RE ENGINE",
        teamSize: "20人（あおっきぃーず）",
        developmentPeriod: "2025年秋",
        developmentOrder: 10,
        teamSizeCount: 20,
        introductionPath: "information/Dream/introduction.txt",
        detailsPath: "information/Dream/details.txt",
    },
    {
        title: "テトリス崩し",
        image: "information/TetrisBreakout/TetrisBreakout_2_Square.png",
        imageAlt: "テトリス崩し",
        detailImages: [
            "information/TetrisBreakout/TetrisBreakout_2.jpg",
            "information/TetrisBreakout/TetrisBreakout_1.png",
        ],
        tags: ["パズル", "対戦", "マルチプレイ", "2D"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2025年冬",
        developmentOrder: 11,
        teamSizeCount: 1,
        introductionPath: "information/TetrisBreakout/introduction.txt",
        detailsPath: "information/TetrisBreakout/details.txt",
    },
    {
        title: "Gravity Golf",
        image: "information/GravityGolf/GravityGolf_Title.png",
        imageAlt: "Gravity Golf",
        detailImages: [
            "information/GravityGolf/GravityGolf_2.png",
            "information/GravityGolf/GravityGolf_1.png",
            "information/GravityGolf/GravityGolf_3.png",
        ],
        tags: ["パズル", "物理", "2D"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2025年冬",
        developmentOrder: 12,
        teamSizeCount: 1,
        introductionPath: "information/GravityGolf/introduction.txt",
        detailsPath: "information/GravityGolf/details.txt",
    },
    {
        title: "VRアクションゲーム",
        image: "information/VRActionGame/VRActionGame_1_Square.jpg",
        imageAlt: "VRアクションゲーム",
        detailImages: [
            "information/VRActionGame/VRActionGame_2.jpg",
            "information/VRActionGame/VRActionGame_1.jpg",
        ],
        tags: ["アクション", "VR", "3D"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2026年春",
        developmentOrder: 13,
        teamSizeCount: 1,
        introductionPath: "information/VRActionGame/introduction.txt",
        detailsPath: "information/VRActionGame/details.txt",
    },
    {
        title: "My1stGame",
        image: "information/My1stGame/My1stGame_Title.png",
        imageAlt: "My1stGame",
        detailImages: [
            "information/My1stGame/My1stGame_2.png",
            "information/My1stGame/My1stGame_1.png",
        ],
        tags: ["物理", "高難度", "2D"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2026年春",
        developmentOrder: 14,
        teamSizeCount: 1,
        introductionPath: "information/My1stGame/introduction.txt",
        detailsPath: "information/My1stGame/details.txt",
    },
    {
        title: "AI順位当てゲーム",
        image: "information/AIGame/AIGame_1_Square.png",
        imageAlt: "AI順位当てゲーム",
        detailImages: [
            "information/AIGame/AIGame_2.png",
            "information/AIGame/AIGame_1.png",
        ],
        tags: ["マルチプレイ"],
        engine: "Unity",
        teamSize: "1人",
        developmentPeriod: "2026年春",
        developmentOrder: 15,
        teamSizeCount: 1,
        introductionPath: "information/AIGame/introduction.txt",
        detailsPath: "information/AIGame/details.txt",
    },
    {
        title: "対称な部屋からの脱出",
        image: "information/Symmetry/Symmetry_Title.png",
        imageAlt: "対称な部屋からの脱出",
        detailImages: [
            "information/Symmetry/Symmetry_1.png",
        ],
        tags: ["脱出", "謎解き", "高難度", "3D"],
        engine: "Unreal Engine",
        teamSize: "1人",
        developmentPeriod: "2026年夏",
        developmentOrder: 16,
        teamSizeCount: 1,
        introductionPath: "information/Symmetry/introduction.txt",
        detailsPath: "information/Symmetry/details.txt",
    },
    {
        title: "Magi Oust Son",
        image: "information/MagiOustSon/MagiOustSon_1_Square.jpg",
        imageAlt: "Magi Oust Son",
        detailImages: [
            "information/MagiOustSon/MagiOustSon_1.jpg",
            "information/MagiOustSon/MagiOustSon_2.jpg",
        ],
        tags: ["アクション", "VR", "3D"],
        engine: "Unity",
        teamSize: "4人（Pf.Sugimoto FC）",
        developmentPeriod: "2026年夏",
        developmentOrder: 17,
        teamSizeCount: 4,
        introductionPath: "information/MagiOustSon/introduction.txt",
        detailsPath: "information/MagiOustSon/details.txt",
    },
    {
        title: "カミシロ村の7日間",
        image: "information/Kamishiro/Yuki_smile2.png",
        imageAlt: "カミシロ村の7日間",
        detailImages: [
            "information/Kamishiro/Kamishiro_1.png",
            "information/Kamishiro/Kamishiro_2.png",
        ],
        tags: ["ノベルゲーム", "2D"],
        engine: "Unity",
        teamSize: "5人",
        developmentPeriod: "2026年夏",
        developmentOrder: 18,
        teamSizeCount: 5,
        introductionPath: "information/Kamishiro/introduction.txt",
        detailsPath: "information/Kamishiro/details.txt",
    },
    {
        title: "よみガエル",
        image: "information/Yomigaeru/Yomigaeru_1_Square.png",
        imageAlt: "カミシロ村の7日間",
        detailImages: [
            "information/Yomigaeru/Yomigaeru_4.jpg",
            "information/Yomigaeru/Yomigaeru_1.png",
            "information/Yomigaeru/Yomigaeru_2.jpg",
            "information/Yomigaeru/Yomigaeru_3.jpg",
        ],
        tags: ["ランゲーム", "アクション", "2D"],
        engine: "Unity",
        teamSize: "3人（ともっきぃーず）",
        developmentPeriod: "2026年夏",
        developmentOrder: 19,
        teamSizeCount: 3,
        introductionPath: "information/Yomigaeru/introduction.txt",
        detailsPath: "information/Yomigaeru/details.txt",
    },
];
